# first stage: build kwkhtmltopdf_server

FROM --platform=linux/amd64 docker.io/golang:1.23.3
WORKDIR /app
COPY go.mod .
COPY go.sum .
COPY . .
RUN go build -o app .

# second stage: server with wkhtmltopdf

FROM --platform=linux/amd64 docker.io/ubuntu:22.04

RUN set -x \
  && apt update \
  && apt -y install --no-install-recommends \
    wget \
    ca-certificates \
    fonts-liberation2 \
    fontconfig \
    libjpeg-turbo8 \
    libx11-6 \
    libxext6 \
    libxrender1 \
    xfonts-75dpi \
    xfonts-base \
    fonts-lato \
  && wget -q -O /tmp/wkhtmltox.deb https://github.com/wkhtmltopdf/packaging/releases/download/0.12.6.1-2/wkhtmltox_0.12.6.1-2.jammy_amd64.deb \
  && echo "800eb1c699d07238fee77bf9df1556964f00ffcf /tmp/wkhtmltox.deb" | sha1sum -c - \
  && dpkg -i /tmp/wkhtmltox.deb \
  && apt -f install \
  && apt -y clean \
  && rm -rf /var/lib/apt/lists/* \
  && rm /tmp/wkhtmltox.deb

RUN wget https://github.com/google/fonts/archive/main.tar.gz -O gf.tar.gz && \
  tar -xf gf.tar.gz && \
  mkdir -p /usr/share/fonts/truetype/google-fonts && \
  find $PWD/fonts-main/ -name "*.ttf" -exec install -m644 {} /usr/share/fonts/truetype/google-fonts/ \; || return 1 && \
  rm -f gf.tar.gz && \
  # Remove the extracted fonts directory
  rm -rf $PWD/fonts-main
#    && \
#   # Remove the following line if you're installing more applications after this RUN command and you have errors while installing them
#   rm -rf /var/cache/* && \
#   fc-cache -f

COPY --from=0 /app/app /usr/local/bin/

RUN adduser --disabled-password --gecos '' kwkhtmltopdf
USER kwkhtmltopdf
ENV LANG=C.UTF-8
ENV LC_ALL=C.UTF-8

EXPOSE 8080
CMD ["/usr/local/bin/app"]
