apiVersion: apps/v1
kind: Deployment
metadata:
  name: wkhtmltopdf
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  selector:
    matchLabels:
      app.kubernetes.io/name: wkhtmltopdf
  template:
    metadata:
      labels:
        app.kubernetes.io/name: wkhtmltopdf
    spec:
      nodeSelector:
        arch: intel
      tolerations:
      - key: fbx.lending/nodepool-family
        operator: "Equal"
        value: "true"
        effect: NoSchedule
      containers:
      - name: wkhtmltopdf
        image: {{ .Values.image.wkhtmltopdf }}
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            cpu: {{ .Values.resources.wkhtmltopdf.limits.cpu }}
            memory: {{ .Values.resources.wkhtmltopdf.limits.memory }}
          requests:
            cpu: {{ .Values.resources.wkhtmltopdf.requests.cpu }}
            memory: {{ .Values.resources.wkhtmltopdf.requests.memory }}
        ports:
        - name: http
          containerPort: {{ .Values.service.wkhtmltopdfPort }}