apiVersion: v1
kind: Service
metadata:
  name: wkhtmltopdf
  namespace: {{ .Values.namespace }}
spec:
  ports:
    - port: 80
      targetPort: {{ .Values.service.wkhtmltopdfPort }}
      protocol: TCP
  type: {{ .Values.service.type }}
  selector:
    app.kubernetes.io/name: wkhtmltopdf