namespace: lending
replicaCount: 1
revisionHistoryLimit: 5

image:
  wkhtmltopdf: TODO

resources:
  wkhtmltopdf:
    limits:
      cpu: 4
      memory: 8Gi
    requests:
      cpu: 2
      memory: 4Gi

service:
  type: NodePort
  wkhtmltopdfPort: 8080
