namespace: lending
replicaCount: 1
revisionHistoryLimit: 5

image:
  wkhtmltopdf: TODO

resources:
  wkhtmltopdf:
    limits:
      cpu: 2
      memory: 4Gi
    requests:
      cpu: 1
      memory: 2Gi

service:
  type: NodePort
  wkhtmltopdfPort: 8080
